// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2026 G4OCCT Contributors

#ifndef G4OCCT_TESTS_GEOMETRY_FIXTURE_RAY_COMPARE_HH
#define G4OCCT_TESTS_GEOMETRY_FIXTURE_RAY_COMPARE_HH

#include "geometry/fixture_manifest.hh"
#include "geometry/fixture_validation.hh"

#include <filesystem>
#include <string>

#include <G4ThreeVector.hh>
#include <G4VSolid.hh>

namespace g4occt::tests::geometry {

/** Options controlling fixture ray-comparison workloads. */
struct FixtureRayComparisonOptions {
  /// Number of deterministic ray directions to compare.
  std::size_t ray_count{2048};
  /// Maximum number of detailed mismatch diagnostics to emit per fixture per
  /// mismatch category (ray intersection, ray distance, ray normal, and
  /// SurfaceNormal each have their own independent cap at this limit).
  std::size_t max_reported_mismatches{8};
  /// Output directory for per-fixture point-cloud JSON files; empty means skip.
  std::filesystem::path point_cloud_dir;
  /// Number of inward-bound rays to fire per bounding-box face (6 faces total).
  /// These surface rays expose interior surface patches that central rays miss
  /// in non-convex solids such as the torus and NIST CTC shapes.
  std::size_t surface_rays_per_face{1024};
};

/** Summary of one fixture's native-vs-imported ray-comparison run. */
struct FixtureRayComparisonSummary {
  std::string fixture_id;
  std::string geant4_class;
  std::size_t ray_count{0};
  std::size_t mismatch_count{0};
  std::size_t normal_mismatch_count{0};
  G4double distance_tolerance{0.0};
  G4ThreeVector native_origin;
  G4ThreeVector imported_origin;
  EInside native_origin_state{kOutside};
  EInside imported_origin_state{kOutside};
  double native_elapsed_ms{0.0};
  double imported_elapsed_ms{0.0};
  /// Total number of bounding-box surface rays fired (6 × surface_rays_per_face).
  std::size_t surface_ray_count{0};
  /// Number of agreed hit points where SurfaceNormal(p) was evaluated.
  std::size_t surface_normal_count{0};
  /// Number of hit points where native and imported SurfaceNormal(p) disagreed.
  std::size_t surface_normal_mismatch_count{0};
  /// Elapsed time for all native SurfaceNormal(p) calls (milliseconds).
  double native_surface_normal_ms{0.0};
  /// Elapsed time for all imported SurfaceNormal(p) calls (milliseconds).
  double imported_surface_normal_ms{0.0};
};

/** Return the default repository fixture manifest path for tests and benchmarks. */
std::filesystem::path DefaultRepositoryManifestPath();

/** Return the Geant4-derived distance tolerance used for ray comparisons. */
G4double DefaultRayComparisonTolerance();

/**
 * Build both fixture models, compare ray hits from a fixture-class-specific
 * comparison origin, and collect timings.
 *
 * After the ray comparison, `SurfaceNormal(p)` is benchmarked at all agreed
 * hit points (rays where both solids agreed on intersection and distance).
 * Native and imported calls are timed separately and their normals are
 * compared with the same dot-product threshold used for ray normals.  For
 * rays that originated inside the solid (DistanceToOut path), the exit normal
 * from Phase 1 is cross-validated against the SurfaceNormal result as an
 * internal consistency check.
 *
 * Validation codes produced by this function include:
 *  - `fixture.ray_origin_state_mismatch`         — origin classification differs.
 *  - `fixture.ray_intersection_mismatch`          — one solid hits, the other misses.
 *  - `fixture.ray_distance_mismatch`              — hit distances disagree beyond tolerance.
 *  - `fixture.ray_normal_mismatch`                — DistanceToOut exit normals disagree.
 *  - `fixture.surface_normal_mismatch`            — SurfaceNormal(p) normals disagree.
 *  - `fixture.surface_ray_intersection_mismatch`  — bounding-box surface ray hit mismatch.
 *  - `fixture.surface_ray_distance_mismatch`      — surface ray distances disagree.
 *
 * The distance tolerance defaults to `DefaultRayComparisonTolerance()` (the Geant4
 * surface tolerance).  Fixtures with approximate STEP representations may specify a
 * larger value via `validation.distance_tolerance_mm` in `provenance.yaml`; this
 * widens the acceptance band for DTI(p,v) and DTO(p,v) distance comparisons to
 * match the expected geometric error of the approximation.
 *
 * The comparison origin is chosen as follows:
 * - `G4Tet`: centroid of the four vertices from the fixture provenance
 *   (`vertices_mm`).  A non-degenerate tetrahedron's centroid is always inside.
 * - `G4TessellatedSolid`: centroid of all `vertices_mm` vertices, validated
 *   at runtime with `Inside()`.  Falls back to the bounding-box centre when
 *   the centroid is `kOutside` (e.g. concave or non-convex meshes).
 * - Ellipsoidal and twisted solids (`G4ScaledSolid`, `G4Ellipsoid`,
 *   `G4EllipticalCone`, `G4EllipticalTube`, and fixtures generated by
 *   `generate_twisted_fixtures`): the coordinate origin `(0, 0, 0)`.
 * - All other solids: the centre of the axis-aligned bounding box.
 */
ValidationReport CompareFixtureRays(const FixtureValidationRequest& request,
                                    const FixtureRayComparisonOptions& options = {},
                                    FixtureRayComparisonSummary* summary       = nullptr);

} // namespace g4occt::tests::geometry

#endif
