// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2026 G4OCCT Contributors

#ifndef G4OCCT_TESTS_GEOMETRY_FIXTURE_INSIDE_COMPARE_HH
#define G4OCCT_TESTS_GEOMETRY_FIXTURE_INSIDE_COMPARE_HH

#include "geometry/fixture_manifest.hh"
#include "geometry/fixture_validation.hh"

#include <cstddef>
#include <string>

namespace g4occt::tests::geometry {

/** Options controlling the `Inside(p)` classification benchmark and comparison. */
struct FixtureInsideComparisonOptions {
  /// Total number of test points to classify (split roughly 50/50 between bounding-box
  /// grid points and near-surface points).
  std::size_t point_count{4096};
  /// Whether to add near-surface points generated by ray-hit offsets.
  ///
  /// Disable this for throughput-oriented benchmarks that should avoid
  /// boundary-adjacent `Inside()` queries, which can trigger pathological OCCT
  /// classifier behaviour on some imported solids.
  bool include_near_surface_points{true};
  /// Maximum number of detailed mismatch diagnostics to emit per fixture.
  std::size_t max_reported_mismatches{8};
};

/** Summary of one fixture's native-vs-imported `Inside(p)` comparison run. */
struct FixtureInsideComparisonSummary {
  /// Qualified fixture identifier (`family/id`).
  std::string fixture_id;
  /// Geant4 class name read from the fixture provenance.
  std::string geant4_class;
  /// Total number of test points classified.
  std::size_t point_count{0};
  /// Number of `kInside`-vs-`kOutside` hard mismatches (errors).
  std::size_t mismatch_count{0};
  /// Number of `kSurface`-vs-`kInside/kOutside` boundary ambiguities (warnings).
  std::size_t surface_ambiguity_count{0};
  /// Elapsed time for all native `Inside()` calls (milliseconds).
  double native_elapsed_ms{0.0};
  /// Elapsed time for all imported `Inside()` calls (milliseconds).
  double imported_elapsed_ms{0.0};
};

/**
 * Build both fixture models, evaluate `Inside(p)` at a deterministic set of
 * test points, compare the classifications, and collect timings.
 *
 * Two categories of test points are used:
 *  - **Bounding-box points** (~50 %): quasi-random points sampled uniformly
 *    from the axis-aligned bounding box using a Halton low-discrepancy
 *    sequence.  These cover the solid interior and exterior and test bulk
 *    classification throughput.
 *  - **Near-surface points** (~50 %): ray hit points obtained by tracing rays
 *    from the bounding-box centre and then offsetting each hit slightly inward
 *    and outward by one surface-tolerance step.  These stress the boundary
 *    region where classification disagreements are most likely.
 *
 * Classification agreement rules:
 *  - `kInside` vs `kOutside` → hard error (`fixture.inside_classification_mismatch`).
 *  - Any mismatch involving `kSurface` → warning (ambiguous boundary).
 *
 * @param request  Fixture and manifest to process.
 * @param options  Tuning parameters (point count, mismatch report limit).
 * @param summary  Optional output struct for timing and mismatch counts.
 * @return         Validation report with info, warning, and error messages.
 */
ValidationReport CompareFixtureInside(const FixtureValidationRequest& request,
                                      const FixtureInsideComparisonOptions& options = {},
                                      FixtureInsideComparisonSummary* summary       = nullptr);

} // namespace g4occt::tests::geometry

#endif
