# cmake-format: off
# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (C) 2026 G4OCCT Contributors
# cmake-format: on

# Coverage instrumentation and report target using bilke/cmake-modules CodeCoverage.
#
# This module is included by the top-level CMakeLists.txt when USE_COVERAGE=ON.
# It configures the compiler-appropriate gcov/llvm-cov tool at CMake configure
# time (eliminating the need for fragile shell-side CMakeCache.txt parsing),
# then defines a `coverage-report` build target that runs ctest and produces an
# HTML report plus a JSON summary via gcovr.
#
# Usage (from the build directory):
#   cmake --build . --target coverage-report
#
# gcovr must be on PATH when the target is invoked.  In CI a venv is used:
#   python3 -m venv .venv-gcovr && .venv-gcovr/bin/pip install gcovr
#   PATH="$(pwd)/.venv-gcovr/bin:$PATH" cmake --build build --target coverage-report

include(FetchContent)

# Pin to a specific commit for reproducibility; bilke/cmake-modules has no tags.
FetchContent_Declare(
  cmake_modules
  GIT_REPOSITORY https://github.com/bilke/cmake-modules.git
  GIT_TAG 5b988b5beb64270cf68b7d6c20298ebc8236b580
)
FetchContent_MakeAvailable(cmake_modules)
list(APPEND CMAKE_MODULE_PATH "${cmake_modules_SOURCE_DIR}")

# ── Detect coverage tool matching the active compiler ────────────────────────
# Look in the compiler's own directory first to avoid version mismatches with
# any system-installed /usr/bin/gcov-* binaries (e.g. the eic_xl container
# mounts the host /usr/bin which may carry a different GCC minor version).
get_filename_component(_cxx_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)

if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  find_program(GCOV_PATH llvm-cov HINTS "${_cxx_dir}")
  if(GCOV_PATH)
    set(_gcov_executable "${GCOV_PATH} gcov")
  else()
    # Fall back to bare command; must be on PATH at build time.
    set(_gcov_executable "llvm-cov gcov")
    set(GCOV_PATH "llvm-cov" CACHE FILEPATH "llvm-cov command for Clang coverage")
  endif()
  message(STATUS "Coverage: Clang compiler; gcov executable: ${_gcov_executable}")
else()
  find_program(GCOV_PATH NAMES gcov gcov-14 gcov-13 HINTS "${_cxx_dir}")
  if(NOT GCOV_PATH)
    message(FATAL_ERROR "gcov not found in '${_cxx_dir}' or on PATH. "
                        "Install gcov or set GCOV_PATH manually.")
  endif()
  set(_gcov_executable "${GCOV_PATH}")
  message(STATUS "Coverage: GCC compiler; gcov executable: ${_gcov_executable}")
endif()

# gcovr is installed into a venv at CI build time and need not exist at
# configure time.  Pre-set the CACHE variable so that CodeCoverage.cmake's
# `if(NOT GCOVR_PATH) → FATAL_ERROR` does not fire during configuration.
if(NOT GCOVR_PATH)
  set(GCOVR_PATH
      "gcovr"
      CACHE FILEPATH "gcovr command; must be on PATH when coverage-report is built")
endif()

# Additional gcovr flags appended after the standard options generated by the
# CodeCoverage module.  Each CMake list element becomes one shell argument
# (VERBATIM in the underlying add_custom_target).  The space inside
# "${_gcov_executable}" for Clang is intentional: gcovr passes the value to
# shlex.split() which splits "llvm-cov gcov" into the correct two-word command.
set(GCOVR_ADDITIONAL_ARGS
    "--gcov-executable"
    "${_gcov_executable}"
    "--filter"
    "/.*/src/G4OCCT[^/]*"
    "--filter"
    "/.*/include/G4OCCT/.*"
    "--json-summary"
    "${CMAKE_BINARY_DIR}/coverage-summary.json"
    "--print-summary")

include(CodeCoverage)

# Add --coverage, -g, -fprofile-abs-path, and (when supported) -fprofile-update=atomic
# to all targets via CMAKE_CXX_FLAGS / CMAKE_C_FLAGS.
append_coverage_compiler_flags()

# Supplement with flags that improve line-level accuracy but are not part of
# the upstream CodeCoverage module's default set.
add_compile_options(-fno-inline -fno-omit-frame-pointer)

# coverage-report target: runs ctest (excluding dd4hep plugin tests, which run
# in their own CI job) and generates an HTML report + JSON summary via gcovr.
include(ProcessorCount)
ProcessorCount(_nproc)
if(_nproc EQUAL 0)
  set(_nproc 1)
endif()

setup_target_for_coverage_gcovr_html(
  NAME coverage-report
  EXECUTABLE ctest
  EXECUTABLE_ARGS --test-dir "${CMAKE_BINARY_DIR}" --output-on-failure -LE dd4hep
                  -j "${_nproc}"
  BASE_DIRECTORY "${CMAKE_SOURCE_DIR}")
