# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (C) 2026 G4OCCT Contributors

name: Base Container

on:
  push:
    branches: [main]
    tags: ['v*']
    paths:
      - '.github/spack.yaml'
  workflow_call:
  workflow_dispatch:

jobs:
  build-base:
    name: Build spack base layer
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Spack
        uses: spack/setup-spack@v3
        with:
          spack_ref: releases/v0.23
          packages_ref: v2025.11.0
          buildcache: false

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install spack environment from EIC buildcache
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: spack-bash {0}
        # spack looks for spack.yaml in the directory given to -e
        run: spack -e .github install

      - name: Push base layer image to GHCR
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          spack -e .github buildcache push \
            --base-image ubuntu:22.04 \
            --tag base \
            --update-index \
            oci://ghcr.io/eic/g4occt
