name: SPDX

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-spdx-headers:
    name: Check SPDX license headers
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check SPDX headers
        uses: enarx/spdx@master
        with:
          licenses: |-
            LGPL-2.1-or-later
          ignore-paths: |-
            src/examples/B1
            src/examples/B4c
